# Generated by Django 5.1.4 on 2024-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
